services:
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest'
    ports:
      - '10000:10000'
      - '10001'
      - '10002'
    volumes:
      - azurite-data:/data
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
volumes:
  azurite-data: