services:
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest'
    ports:
      - '10000:10000'
      - '10001'
      - '10002'
    volumes:
      - azurite-data:/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
volumes:
  azurite-data: